### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by KiddoV** [stunndard/golangwin7patch#3]
My app is built with [Wails](https://github.com/wailsapp/wails).
I also use [NPX](https://github.com/upx/upx) when compile the Go app.

I got this error when trying your patcher:
```txt
couldn't find the required data to patch
file not changed.
```

Can u tell what is wrong?

**Comment by stunndard** [comment]
You don't want to use UPX, as packed or protected executables cannot be patched. You can, however, patch it first and pack it after.

**Comment by KiddoV** [comment]
What do you mean by `patch it first and pack it after`?

**Comment by stunndard** [comment]
Do not use UPX and the patcher will work. You can still use UPX *after* the patching is done.

**Comment by KiddoV** [comment]
Got it. Thanks!
